// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { FaWhatsapp } from "react-icons/fa";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Load Montserrat font from Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        style={{
          fontFamily: "Montserrat, Helvetica, Arial, sans-serif",
        }}
        className="antialiased overflow-x-hidden"
      >
        {children}

        {/* WhatsApp Floating Icon */}
        <a
          href="https://wa.me/918600181189"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="WhatsApp"
          className="fixed bottom-6 right-6 z-50 bg-white rounded-full shadow-lg p-3 flex items-center justify-center hover:bg-gray-200 transition-colors"
          style={{ boxShadow: "0 2px 12px rgba(0,0,0,0.15)" }}
        >
          <FaWhatsapp size={28} color="#111" />
        </a>
      </body>
    </html>
  );
}
