import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { FaWhatsapp } from 'react-icons/fa';

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      <body
        className={`${montserrat.variable} antialiased overflow-x-hidden`}
      >
        {children}
        {/* WhatsApp Floating Icon */}
        <a
          href="https://wa.me/918600181189"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="WhatsApp"
          className="fixed bottom-6 right-6 z-50 bg-white rounded-full shadow-lg p-3 flex items-center justify-center hover:bg-gray-200 transition-colors"
          style={{ boxShadow: '0 2px 12px rgba(0,0,0,0.15)' }}
        >
          <FaWhatsapp size={28} color="#111" />
        </a>
      </body>
    </html>
  );
}
